### ISSUE TITLE
Collapse commits without benchmark data

### ISSUE THREAD

**Issue by upsj** [pse-parkview/PSE_dashboard#114]
Instead of listing all commits between two commits without benchmark data, maybe we could collapse them like

```
> Benchmarked commit

v Benchmarked commit
   non-benchmarked commit
   non-benchmarked commit 2
   ...
```

Not sure how this would/should interact with pagination though.

**Comment by taDachs** [comment]
This is the behavior since #132:

https://user-images.githubusercontent.com/22925374/162626475-b87cc3b8-2538-49c2-b3f9-ce449669ea1c.mp4


I would replace the "hide" button with something like "collaps/fold". When the option is enabled all the non-benchmarked commits get collapsed as described. Maybe give them a nice header like "20 commits without benchmark"

**Comment by taDachs** [comment]
And this would be the behavior on #136

https://user-images.githubusercontent.com/22925374/162640081-f83388f0-667a-4191-b4aa-a3b2eaf8f939.mp4
